# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d09ac669b8d64d7b519e71e13cab4f7ff3f2be508eb118dd5dfd79fc5724707468858e7f23805dc318828031eb9db0535358c71dd3169010a230d51cdfb29134

test:
  secret_key_base: 03034324910d99df47b57425f6dd280a983affa61bd78c888abd5a3dcf735c2459fd8d59ee1bf36e0bdc7d66ec2ede832617197ae635e1445ba221c5da127b56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
